import type { DisplayElementInput } from "@/lib/endpoints";

export interface TemplatePreset {
  key: string;
  label: string;
  description: string;
  canvas: { width: number; height: number; background_color: string };
  elements: DisplayElementInput[];
}

function el(partial: Partial<DisplayElementInput> & Pick<DisplayElementInput, "type" | "x" | "y" | "width" | "height">): DisplayElementInput {
  return {
    z_index: 0,
    style: {},
    binding: {},
    is_locked: false,
    is_hidden: false,
    ...partial,
  };
}

export const TEMPLATE_PRESETS: TemplatePreset[] = [
  {
    key: "minimal-count",
    label: "Minimal Count",
    description: "Just the number, large and centered. Nothing to distract from it.",
    canvas: { width: 1920, height: 1080, background_color: "#0b1220" },
    elements: [
      el({
        type: "heading",
        x: 160,
        y: 120,
        width: 1600,
        height: 140,
        z_index: 1,
        style: { font_size: 72, color: "#e2e8f0", text_align: "center" },
        binding: { text: "Live Giving" },
      }),
      el({
        type: "contribution_count",
        x: 310,
        y: 340,
        width: 1300,
        height: 420,
        z_index: 2,
        style: { font_size: 280, color: "#60a5fa", text_align: "center" },
      }),
      el({
        type: "body_text",
        x: 310,
        y: 800,
        width: 1300,
        height: 80,
        z_index: 3,
        style: { font_size: 36, color: "#94a3b8", text_align: "center" },
        binding: { text: "contributions and counting" },
      }),
      el({
        type: "countdown",
        x: 1650,
        y: 40,
        width: 220,
        height: 90,
        z_index: 4,
        style: { font_size: 40, color: "#f1f5f9", text_align: "right" },
      }),
    ],
  },
  {
    key: "goal-thermometer",
    label: "Goal Thermometer",
    description: "A progress bar toward the session's goal, with the count and amount side by side.",
    canvas: { width: 1920, height: 1080, background_color: "#111827" },
    elements: [
      el({
        type: "heading",
        x: 100,
        y: 60,
        width: 1720,
        height: 110,
        z_index: 1,
        style: { font_size: 60, color: "#f9fafb", text_align: "center" },
        binding: { text: "Together We Give" },
      }),
      el({
        type: "goal",
        x: 100,
        y: 200,
        width: 1720,
        height: 90,
        z_index: 2,
        style: { font_size: 44, color: "#facc15", text_align: "center" },
      }),
      el({
        type: "progress_bar",
        x: 160,
        y: 320,
        width: 1600,
        height: 60,
        z_index: 3,
        style: { background_color: "#1f2937" },
      }),
      el({
        type: "amount",
        x: 160,
        y: 420,
        width: 760,
        height: 260,
        z_index: 4,
        style: { font_size: 140, color: "#34d399", text_align: "center" },
      }),
      el({
        type: "contribution_count",
        x: 1000,
        y: 420,
        width: 760,
        height: 260,
        z_index: 5,
        style: { font_size: 140, color: "#60a5fa", text_align: "center" },
      }),
      el({
        type: "body_text",
        x: 160,
        y: 700,
        width: 760,
        height: 60,
        z_index: 6,
        style: { font_size: 32, color: "#9ca3af", text_align: "center" },
        binding: { text: "raised" },
      }),
      el({
        type: "body_text",
        x: 1000,
        y: 700,
        width: 760,
        height: 60,
        z_index: 7,
        style: { font_size: 32, color: "#9ca3af", text_align: "center" },
        binding: { text: "gifts" },
      }),
    ],
  },
  {
    key: "bold-announcement",
    label: "Bold Announcement",
    description: "Big logo and amount for a moment of celebration -- end of a campaign, a big milestone.",
    canvas: { width: 1920, height: 1080, background_color: "#0f172a" },
    elements: [
      el({
        type: "logo",
        x: 760,
        y: 60,
        width: 400,
        height: 160,
        z_index: 1,
      }),
      el({
        type: "heading",
        x: 160,
        y: 260,
        width: 1600,
        height: 120,
        z_index: 2,
        style: { font_size: 64, color: "#f8fafc", text_align: "center" },
        binding: { text: "Thank You For Giving" },
      }),
      el({
        type: "amount",
        x: 310,
        y: 420,
        width: 1300,
        height: 340,
        z_index: 3,
        style: { font_size: 220, color: "#fbbf24", text_align: "center" },
      }),
      el({
        type: "sponsor_message",
        x: 0,
        y: 960,
        width: 1920,
        height: 100,
        z_index: 4,
        style: { font_size: 32, color: "#cbd5e1", text_align: "center", background_color: "rgba(255,255,255,0.05)" },
        binding: { text: "Every gift makes a difference. Thank you for your generosity." },
      }),
    ],
  },
  {
    key: "qr-and-give",
    label: "QR & Give",
    description: "Payment instructions and a scannable QR code alongside the running count -- built for a giving/offering moment.",
    canvas: { width: 1920, height: 1080, background_color: "#0b1220" },
    elements: [
      el({
        type: "heading",
        x: 100,
        y: 80,
        width: 1100,
        height: 120,
        z_index: 1,
        style: { font_size: 56, color: "#f1f5f9", text_align: "left" },
        binding: { text: "Give Right Now" },
      }),
      el({
        type: "payment_instructions",
        x: 100,
        y: 240,
        width: 1100,
        height: 300,
        z_index: 2,
        style: { font_size: 34, color: "#cbd5e1", text_align: "left" },
        binding: { text: "Scan the QR code, or e-transfer to give@yourchurch.org" },
      }),
      el({
        type: "contribution_count",
        x: 100,
        y: 580,
        width: 520,
        height: 220,
        z_index: 3,
        style: { font_size: 120, color: "#60a5fa", text_align: "left" },
      }),
      el({
        type: "body_text",
        x: 100,
        y: 800,
        width: 520,
        height: 60,
        z_index: 4,
        style: { font_size: 28, color: "#94a3b8", text_align: "left" },
        binding: { text: "have given today" },
      }),
      el({
        type: "qr_code",
        x: 1360,
        y: 240,
        width: 460,
        height: 460,
        z_index: 5,
      }),
      el({
        type: "countdown",
        x: 1650,
        y: 80,
        width: 220,
        height: 90,
        z_index: 6,
        style: { font_size: 40, color: "#f1f5f9", text_align: "right" },
      }),
    ],
  },
];
